debug: false
uuid: 3fab1623-d84a-448e-8f72-716647430378
token_id: R7njDGGu4wFmC8qm
token: 9hEKlm9KKCyNYgIfAoatrJUO7iJuvOhfOD3BkSUMq34O172llcuMiKENMAJoF5Hk
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/certs/fullchain.pem
    key: /etc/certs/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://panel.nishantapps.in'
